Option to block NSFW results
jmakhack/myanimelist-cli pull request #60
Opened 2022-10-09 14:48 UTC by sameersecond

Closes #56 

Added the option `-s`, which limits the anime fetched from the API to only SFW (Safe For Work).
This option can be used with the other options for fetching anime.

2022-10-10 03:04 UTC, jmakhack requested changes
Hey @sameersecond, your changes look good overall! Just requesting a very minor style change.

I'll test this feature in a bit and if it all looks good, I'll approve your PR :)

Note: don't worry about the Codacy warnings/errors

2022-10-10 03:04 UTC, jmakhack commented on README.md
> +  -s, --sfw                  Fetch only SFW anime
Thanks for making this docs change as well :)

2022-10-10 12:48 UTC, sameersecond commented on src/mya.c
> +	if(allow_nsfw == 1)
Sure

2022-10-11 01:47 UTC, jmakhack approved these changes
Just tested your changes on my virtual machine and it looks good, @sameersecond.

Thanks for the contribution!

2022-10-11 01:49 UTC, jmakhack commented
@all-contributors please add @sameersecond for code and docs

2022-10-11 01:50 UTC, merged