Bug-Fix-70/69
jmakhack/myanimelist-cli pull request #77
Opened 2022-10-17 07:25 UTC by The-Debarghya

## Associated Issue

Closes #70 #69 

## Implemented Solution

- Replaced `strcpy` functions with `strncpy` where the buffer value was kept as static string length and added BUFFER as a macro for `strncpy(uri, json_object_get_string(next), BUFFER)` this particular case.
- Replaced `strcat` functions with `strncat` where the max concat length was specified as static strings otherwise a macro MAX_ENDPOINT_LENGTH was used in this case: `strncat(uri, endpoint, MAX_ENDPOINT_LENGTH);` and for this case `strncat(uri, username, MAX_USERNAME_LENGTH)`, a predefined macro MAX_USERNAME_LENGTH was used.

2022-10-18 08:12 UTC, jmakhack requested changes
@The-Debarghya the changes look great overall! I'll test the code when I have time tomorrow and get this approved afterwards.

2022-10-18 10:23 UTC, The-Debarghya commented
I guess I forgot that I had to add libbsd as a dependency, I have added that to the workflow and the makefile.

2022-10-19 02:11 UTC, jmakhack commented
@The-Debarghya Can you take a look at the following build error?

```shell
Run make all
gcc -c -g -Wall src/mya.c -o obj/mya.o
src/mya.c: In function ‘generate_endpoint’:
src/mya.c:253:3: error: a label can only be part of a statement and a declaration is not a statement
  253 |   const char* s = "completed";
      |   ^~~~~
make: *** [Makefile:41: obj/mya.o] Error 1
Error: Process completed with exit code 2.
```

Can you also leave a comment in #69 so I can assign that issue to you too :)

2022-10-19 03:16 UTC, The-Debarghya commented
Can it be merged now?

2022-10-19 03:37 UTC, jmakhack approved these changes
Your changes all look good @The-Debarghya. Thanks a bunch for the contribution! :)

It would also be good to update https://github.com/jmakhack/myanimelist-cli/blob/master/CONTRIBUTING.md#included-libraries with the new included library as well (if you'd like to include that in this PR). I'll add you as a contributor for code and docs.

2022-10-19 03:38 UTC, jmakhack commented
@all-contributors please add @The-Debarghya for code

2022-10-19 03:39 UTC, merged